In [2]:
import pandas as pd

In [6]:
df = pd.read_excel("Pivot SEH AMC uit data CBS.xlsx", sheet_name=2, skiprows=7)
df = df[['Regioletter', '#KaartTNO']]
df

    Regioletter #KaartTNO
0             A        58
1             A        49
2             A        50
3             A        61
4             A        62
..          ...       ...
98            W        47
99            W        60
100           W        68
101           W         x
102           W        85

[103 rows x 2 columns]

In [17]:
dct = {key: value 
       for key, value in zip(df['#KaartTNO'], df['Regioletter'])
       if key != 'x'}
dct

{58: 'A',
 49: 'A',
 50: 'A',
 61: 'A',
 62: 'A',
 63: 'A',
 23: 'B',
 18: 'B',
 17: 'B',
 9: 'C',
 51: 'C',
 52: 'C',
 80: 'C',
 4: 'D',
 78: 'D',
 81: 'D',
 3: 'E',
 38: 'E',
 40: 'E',
 32: 'F',
 31: 'F',
 29: 'F',
 55: 'F',
 33: 'G',
 34: 'G',
 41: 'G',
 24: 'G',
 25: 'G',
 20: 'H',
 2: 'I',
 28: 'I',
 57: 'I',
 1: 'J',
 10: 'J',
 11: 'J',
 30: 'J',
 86: 'J',
 46: 'K',
 69: 'K',
 70: 'K',
 83: 'K',
 84: 'K',
 16: 'L',
 66: 'L',
 76: 'L',
 65: 'L',
 6: 'M',
 21: 'M',
 22: 'M',
 37: 'M',
 7: 'N',
 48: 'N',
 45: 'N',
 15: 'O',
 36: 'O',
 35: 'O',
 59: 'O',
 14: 'P',
 72: 'P',
 71: 'P',
 73: 'P',
 79: 'P',
 27: 'Q',
 26: 'Q',
 56: 'Q',
 82: 'Q',
 8: 'R',
 12: 'R',
 54: 'R',
 13: 'S',
 44: 'S',
 64: 'S',
 19: 'T',
 42: 'T',
 67: 'T',
 77: 'T',
 39: 'U',
 0: 'U',
 87: 'U',
 88: 'U',
 43: 'V',
 53: 'V',
 74: 'V',
 47: 'W',
 60: 'W',
 68: 'W',
 85: 'W'}

In [18]:
import json
with open('knmiregios.json', 'w') as filepath:
    json.dump(dct, filepath)